In [1]:
from numpy import *

data = array([[1,2,3],[4,5,6]])

print data

[[1 2 3]
 [4 5 6]]


In [2]:
print data.shape

(2, 3)


In [3]:
zero_matrix = zeros((2,4))
print zero_matrix

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [4]:
one_matrix = ones((2,4))
print one_matrix

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [5]:
random_matrix = random.randint(10, size = (3,5))
print random_matrix

[[1 7 6 7 8]
 [2 4 9 0 8]
 [6 3 4 5 1]]


In [6]:
print zero_matrix[0][1]

0.0


In [7]:
print zero_matrix[0]

[ 0.  0.  0.  0.]


In [8]:
col_vector = random.randint(10, size = (10,1))
print col_vector

[[0]
 [6]
 [7]
 [3]
 [1]
 [8]
 [2]
 [1]
 [6]
 [1]]


In [10]:
print random_matrix[0, 2]

6


In [11]:
print random_matrix[: , 0:1]

[[1]
 [2]
 [6]]


In [12]:
print random_matrix[ : , 0]
# see difference with last one.. 

[1 2 6]


In [13]:
cols = array([1,2,3])
print random_matrix[0, cols]

[7 6 7]


In [14]:
cols = array([[1,2,3]])
print random_matrix[0, cols]

[[7 6 7]]


In [15]:
flattened = random_matrix.flatten()
print flattened

[1 7 6 7 8 2 4 9 0 8 6 3 4 5 1]


In [19]:
random_matrix2 = random.randint(10, size = (5,3))
# carefully see size of matrix before dot product => (a*b) . (b*c)
dot_product = random_matrix2.dot(random_matrix)
print dot_product

[[ 24  60  71  52  74]
 [ 41  81 103  69 100]
 [ 34  90 119  66 122]
 [ 46  58  75  58  62]
 [ 59  71  89  75  72]]
